import express from 'express';
import { env } from './config/env.js';
import { errorHandler } from './middleware/error-handler.js';
import { notFound } from './middleware/not-found.js';
import { healthRouter } from './routes/health.routes.js';
import { rtiAnalysisRouter } from './routes/rti-analysis.routes.js';
import { rtiAuthorityRouter } from './routes/rti-authority.routes.js';
import { rtiDraftRouter } from './routes/rti-draft.routes.js';
import { rtiReviewRouter } from './routes/rti-review.routes.js';
import { rtiPaymentRouter } from './routes/rti-payment.routes.js';
import { rtiApplicationRouter } from './routes/rti-application.routes.js';
import { rtiTrackingRouter } from './routes/rti-tracking.routes.js';
import { rtiReplyRouter } from './routes/rti-reply.routes.js';
import { rtiAppealRouter } from './routes/rti-appeal.routes.js';
import { demoRouter } from './routes/demo.routes.js';
import { authRouter } from './routes/auth.routes.js';
import { rtiKnowledgeRouter } from './routes/rti-knowledge.routes.js';
import { applicationPersistenceBarrier } from './middleware/application-persistence-barrier.js';
import { corsPolicy } from './middleware/cors.js';
import { securityHeaders } from './middleware/security-headers.js';
import { health } from './controllers/health.controller.js';

export const app = express();

app.disable('x-powered-by');
app.use(securityHeaders);
app.use(corsPolicy);
app.use(express.json({ limit: env.JSON_BODY_LIMIT, strict: true }));
app.use(applicationPersistenceBarrier);
app.get('/health', health);
app.use('/api/rti', rtiAnalysisRouter);
app.use('/api/rti', rtiAuthorityRouter);
app.use('/api/rti', rtiDraftRouter);
app.use('/api/rti', rtiReviewRouter);
app.use('/api/rti', rtiPaymentRouter);
app.use('/api/rti', rtiApplicationRouter);
app.use('/api/rti', rtiTrackingRouter);
app.use('/api/rti', rtiReplyRouter);
app.use('/api/rti', rtiAppealRouter);
app.use('/api/rti', rtiKnowledgeRouter);
app.use('/api/demo', demoRouter);
app.use('/api/auth', authRouter);
app.use('/api/v1/health', healthRouter);
app.use(notFound);
app.use(errorHandler);
